import { db } from '@/db';
import { dishes } from '@/db/schema';

async function main() {
    const sampleDishes = [
        // Appetizers (4 dishes)
        {
            name: 'Samosa Chaat',
            description: 'Crispy samosas topped with chickpeas, yogurt, and tangy chutneys',
            category: 'Appetizers',
            price: '$9',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Paneer Tikka',
            description: 'Grilled cottage cheese marinated in aromatic spices',
            category: 'Appetizers',
            price: '$11',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chicken 65',
            description: 'Spicy, deep-fried chicken with curry leaves and green chilies',
            category: 'Appetizers',
            price: '$12',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Vegetable Pakora',
            description: 'Mixed vegetable fritters with mint chutney',
            category: 'Appetizers',
            price: '$8',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // North Indian (5 dishes)
        {
            name: 'Butter Chicken',
            description: 'Tender chicken in rich tomato and cream sauce',
            category: 'North Indian',
            price: '$18',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Lamb Rogan Josh',
            description: 'Slow-cooked lamb in aromatic Kashmiri spices',
            category: 'North Indian',
            price: '$20',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Palak Paneer',
            description: 'Cottage cheese cubes in creamy spinach gravy',
            category: 'North Indian',
            price: '$15',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Chicken Tikka Masala',
            description: 'Grilled chicken in spiced tomato cream sauce',
            category: 'North Indian',
            price: '$18',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Dal Makhani',
            description: 'Black lentils slow-cooked with butter and cream',
            category: 'North Indian',
            price: '$14',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // South Indian (4 dishes)
        {
            name: 'Masala Dosa',
            description: 'Crispy rice crepe filled with spiced potato, served with sambar and chutney',
            category: 'South Indian',
            price: '$14',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Hyderabadi Biryani',
            description: 'Fragrant basmati rice layered with marinated chicken and saffron',
            category: 'South Indian',
            price: '$18',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Idli Sambar',
            description: 'Steamed rice cakes served with lentil soup and coconut chutney',
            category: 'South Indian',
            price: '$12',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Kerala Fish Curry',
            description: 'Fresh fish simmered in coconut milk with curry leaves',
            category: 'South Indian',
            price: '$17',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Cocktails (3 drinks)
        {
            name: 'Mango Mojito',
            description: 'Fresh mango puree with mint, lime, and soda',
            category: 'Cocktails',
            price: '$12',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Spiced Gin & Tonic',
            description: 'Premium gin with cardamom and cucumber',
            category: 'Cocktails',
            price: '$14',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Rose Lassi Martini',
            description: 'Vodka-based cocktail with rose water and cardamom',
            category: 'Cocktails',
            price: '$13',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Desserts (2 items)
        {
            name: 'Gulab Jamun',
            description: 'Warm milk dumplings in cardamom syrup',
            category: 'Desserts',
            price: '$8',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mango Kulfi',
            description: 'Traditional Indian ice cream with pistachios',
            category: 'Desserts',
            price: '$9',
            imageUrl: null,
            isAvailable: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(dishes).values(sampleDishes);
    
    console.log('✅ Dishes seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});