import { db } from '@/db';
import { pageContents } from '@/db/schema';

async function main() {
    const timestamp = new Date().toISOString();
    
    const samplePageContents = [
        // HOME PAGE (18 records)
        // Hero Section
        {
            page: 'home',
            section: 'hero',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'SIRI Indian Kitchen & Cocktails',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'hero',
            contentType: 'text',
            fieldName: 'subtitle',
            fieldValue: 'Experience the authentic flavors of North & South Indian cuisine paired with innovative craft cocktails',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Concept Section
        {
            page: 'home',
            section: 'concept',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'The SIRI Experience',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'concept',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'A fusion of traditional Indian flavors and modern culinary techniques, creating an unforgettable dining experience',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Highlight 1
        {
            page: 'home',
            section: 'highlight_1',
            contentType: 'text',
            fieldName: 'icon',
            fieldValue: 'chef-hat',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'highlight_1',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Authentic Recipes',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'highlight_1',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Traditional recipes passed down through generations, prepared with authentic spices and techniques',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Highlight 2
        {
            page: 'home',
            section: 'highlight_2',
            contentType: 'text',
            fieldName: 'icon',
            fieldValue: 'cocktail',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'highlight_2',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Craft Cocktails',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'highlight_2',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Innovative cocktails inspired by Indian flavors, crafted by expert mixologists',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Highlight 3
        {
            page: 'home',
            section: 'highlight_3',
            contentType: 'text',
            fieldName: 'icon',
            fieldValue: 'sparkles',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'highlight_3',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Premium Ambiance',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'highlight_3',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Elegant dining atmosphere that combines modern sophistication with Indian heritage',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Journey Section
        {
            page: 'home',
            section: 'journey',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'A Culinary Journey Through India',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'journey',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'From the tandoors of North India to the coconut groves of the South, experience the diverse flavors of Indian cuisine',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'journey',
            contentType: 'image',
            fieldName: 'image',
            fieldValue: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/restaurant-1764634964836.jpg',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // CTA Section
        {
            page: 'home',
            section: 'cta',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Reserve Your Table',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'home',
            section: 'cta',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Join us for an unforgettable dining experience. Book your reservation today.',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },

        // ABOUT PAGE (21 records)
        // Hero Section
        {
            page: 'about',
            section: 'hero',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Our Story',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'hero',
            contentType: 'text',
            fieldName: 'subtitle',
            fieldValue: 'A passion for authentic Indian cuisine meets innovative culinary artistry',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'hero',
            contentType: 'image',
            fieldName: 'image',
            fieldValue: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/image-1765004456427.jpg',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Story Section
        {
            page: 'about',
            section: 'story',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Our Heritage',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'story',
            contentType: 'text',
            fieldName: 'paragraph_1',
            fieldValue: 'SIRI Indian Kitchen & Cocktails was born from a dream to bring authentic Indian flavors to New Jersey while creating a modern dining experience. Our founders, inspired by their Indian heritage and culinary training, envisioned a restaurant that honors traditional recipes while embracing contemporary techniques.',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'story',
            contentType: 'text',
            fieldName: 'paragraph_2',
            fieldValue: 'Every dish we serve tells a story of India\'s rich culinary traditions, carefully crafted with imported spices and fresh, locally-sourced ingredients. Our commitment to excellence extends beyond the kitchen to create a warm, welcoming atmosphere where every guest feels like family.',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Team Member 1
        {
            page: 'about',
            section: 'team_member_1',
            contentType: 'text',
            fieldName: 'name',
            fieldValue: 'Amit',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'team_member_1',
            contentType: 'text',
            fieldName: 'role',
            fieldValue: 'Executive Chef',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'team_member_1',
            contentType: 'image',
            fieldName: 'image',
            fieldValue: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/amith-ji-1764538805166.png',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'team_member_1',
            contentType: 'text',
            fieldName: 'bio',
            fieldValue: 'With over 15 years of culinary experience, Chef Amit brings authentic North Indian flavors to every dish. Trained in traditional tandoor techniques and modern fusion cuisine, he leads our kitchen with passion and precision.',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Team Member 2
        {
            page: 'about',
            section: 'team_member_2',
            contentType: 'text',
            fieldName: 'name',
            fieldValue: 'Neeraj Shokeen',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'team_member_2',
            contentType: 'text',
            fieldName: 'role',
            fieldValue: 'Co-Founder & Managing Director',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'team_member_2',
            contentType: 'image',
            fieldName: 'image',
            fieldValue: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/neeraj-ji-1764633986417.png',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'team_member_2',
            contentType: 'text',
            fieldName: 'bio',
            fieldValue: 'Neeraj\'s vision and dedication have shaped SIRI into a premier dining destination. His commitment to hospitality excellence ensures every guest experiences the warmth and richness of Indian culture.',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Values Section
        {
            page: 'about',
            section: 'values',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Our Values',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'values',
            contentType: 'text',
            fieldName: 'value_1_title',
            fieldValue: 'Authenticity',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'values',
            contentType: 'text',
            fieldName: 'value_1_description',
            fieldValue: 'We honor traditional recipes and cooking methods, using authentic spices and ingredients imported directly from India',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'values',
            contentType: 'text',
            fieldName: 'value_2_title',
            fieldValue: 'Quality',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'values',
            contentType: 'text',
            fieldName: 'value_2_description',
            fieldValue: 'Every ingredient is carefully selected, every dish meticulously prepared to deliver exceptional taste and presentation',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'values',
            contentType: 'text',
            fieldName: 'value_3_title',
            fieldValue: 'Hospitality',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'about',
            section: 'values',
            contentType: 'text',
            fieldName: 'value_3_description',
            fieldValue: 'We treat every guest as family, creating memorable experiences through warm service and genuine care',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },

        // EXPERIENCE PAGE (14 records)
        // Hero Section
        {
            page: 'experience',
            section: 'hero',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'The SIRI Experience',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'hero',
            contentType: 'text',
            fieldName: 'subtitle',
            fieldValue: 'Immerse yourself in a world of flavors, aromas, and traditions',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'hero',
            contentType: 'image',
            fieldName: 'image',
            fieldValue: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/cinematic-aesthetic-shot-of-authentic-indian-fine-1765006382463.png',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Service 1
        {
            page: 'experience',
            section: 'service_1',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Fine Dining',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'service_1',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Experience elevated Indian cuisine in our elegant dining room, where traditional flavors meet contemporary presentation',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'service_1',
            contentType: 'text',
            fieldName: 'hours',
            fieldValue: 'Tuesday - Sunday: 5:00 PM - 10:00 PM',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'service_1',
            contentType: 'image',
            fieldName: 'image',
            fieldValue: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/elevated-dining-1764987220689.jpg',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Service 2
        {
            page: 'experience',
            section: 'service_2',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Cocktail Bar',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'service_2',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Discover innovative cocktails infused with Indian spices and botanicals, crafted by our expert mixologists',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'service_2',
            contentType: 'text',
            fieldName: 'hours',
            fieldValue: 'Tuesday - Sunday: 4:30 PM - 11:00 PM',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Service 3
        {
            page: 'experience',
            section: 'service_3',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Private Events',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'service_3',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Host your special celebrations in our private dining spaces, with customized menus and dedicated service',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Ambiance Section
        {
            page: 'experience',
            section: 'ambiance',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Elegant Atmosphere',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'experience',
            section: 'ambiance',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Modern design meets Indian heritage in our thoughtfully curated space, creating the perfect setting for memorable dining',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },

        // MENU PAGE (3 records)
        {
            page: 'menu',
            section: 'hero',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Our Menu',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'menu',
            section: 'hero',
            contentType: 'text',
            fieldName: 'subtitle',
            fieldValue: 'A curated selection of North and South Indian specialties',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'menu',
            section: 'hero',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Explore our diverse menu featuring traditional tandoori dishes, aromatic curries, fresh seafood, and innovative vegetarian creations',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },

        // CATERING PAGE (11 records)
        // Hero Section
        {
            page: 'catering',
            section: 'hero',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Catering Services',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'catering',
            section: 'hero',
            contentType: 'text',
            fieldName: 'subtitle',
            fieldValue: 'Bring the SIRI experience to your event',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'catering',
            section: 'hero',
            contentType: 'image',
            fieldName: 'image',
            fieldValue: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/render/image/public/document-uploads/cinematic-shot-of-elaborate-indian-catering-setup-1765004927145.png',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Intro Section
        {
            page: 'catering',
            section: 'intro',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Exceptional Catering for Every Occasion',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'catering',
            section: 'intro',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'From intimate gatherings to grand celebrations, our catering services deliver authentic Indian cuisine with professional service and elegant presentation',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Service Type 1
        {
            page: 'catering',
            section: 'service_type_1',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Corporate Events',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'catering',
            section: 'service_type_1',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Impress your clients and colleagues with sophisticated Indian cuisine for business lunches, conferences, and corporate celebrations',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Service Type 2
        {
            page: 'catering',
            section: 'service_type_2',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Wedding & Social Events',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'catering',
            section: 'service_type_2',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Create unforgettable memories with customized menus for weddings, anniversaries, and milestone celebrations',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Service Type 3
        {
            page: 'catering',
            section: 'service_type_3',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Private Parties',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'catering',
            section: 'service_type_3',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Elevate your home gathering with restaurant-quality Indian cuisine delivered and served with care',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },

        // CONTACT PAGE (10 records)
        // Hero Section
        {
            page: 'contact',
            section: 'hero',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Visit Us',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'contact',
            section: 'hero',
            contentType: 'text',
            fieldName: 'subtitle',
            fieldValue: 'We look forward to welcoming you',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Location Section
        {
            page: 'contact',
            section: 'location',
            contentType: 'text',
            fieldName: 'address',
            fieldValue: '275 Rte 4 West, Paramus, NJ 07652, United States',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'contact',
            section: 'location',
            contentType: 'text',
            fieldName: 'phone',
            fieldValue: '(555) 123-4567',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'contact',
            section: 'location',
            contentType: 'text',
            fieldName: 'email',
            fieldValue: 'info@sirirestaurant.com',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Hours Section
        {
            page: 'contact',
            section: 'hours',
            contentType: 'text',
            fieldName: 'mon_thu',
            fieldValue: 'Closed',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'contact',
            section: 'hours',
            contentType: 'text',
            fieldName: 'fri_sat',
            fieldValue: '5:00 PM - 10:30 PM',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'contact',
            section: 'hours',
            contentType: 'text',
            fieldName: 'sun',
            fieldValue: '5:00 PM - 10:00 PM',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        // Directions Section
        {
            page: 'contact',
            section: 'directions',
            contentType: 'text',
            fieldName: 'title',
            fieldValue: 'Getting Here',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            page: 'contact',
            section: 'directions',
            contentType: 'text',
            fieldName: 'description',
            fieldValue: 'Conveniently located on Route 4 West in Paramus, with ample parking available. Easily accessible from major highways including Garden State Parkway and Route 17.',
            displayOrder: 0,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
    ];

    await db.insert(pageContents).values(samplePageContents);
    
    console.log('✅ Page contents seeder completed successfully');
    console.log(`📊 Inserted ${samplePageContents.length} records`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
    process.exit(1);
});